/*
 * Copyright (c) 2017 Mark Ryan
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include <stdbool.h>

#include "keywords.h"

/* clang-format off */
const subtilis_keyword_t subtilis_keywords_list[] = {
	{"ABS",       SUBTILIS_KEYWORD_ABS,          true},
	{"ACS",       SUBTILIS_KEYWORD_ACS,          true},
	{"ADVAL",     SUBTILIS_KEYWORD_ADVAL,        true},
	{"AND",       SUBTILIS_KEYWORD_AND,          true},
	{"APPEND",    SUBTILIS_KEYWORD_APPEND,       false},
	{"ASC",       SUBTILIS_KEYWORD_ASC,          true},
	{"ASN",       SUBTILIS_KEYWORD_ASN,          true},
	{"ATN",       SUBTILIS_KEYWORD_ATN,          true},
	{"AUTO",      SUBTILIS_KEYWORD_AUTO,         false},
	{"BEAT",      SUBTILIS_KEYWORD_BEAT,         true},
	{"BEATS",     SUBTILIS_KEYWORD_BEATS,        true},
	{"BGET#",     SUBTILIS_KEYWORD_BGET_HASH,    true},
	{"BPUT#",     SUBTILIS_KEYWORD_BPUT_HASH,    true},
	{"BY",        SUBTILIS_KEYWORD_BY,           true},
	{"CALL",      SUBTILIS_KEYWORD_CALL,         true},
	{"CASE",      SUBTILIS_KEYWORD_CASE,         true},
	{"CHAIN",     SUBTILIS_KEYWORD_CHAIN,        false},
	{"CHR$",      SUBTILIS_KEYWORD_CHR_STR,      true},
	{"CIRCLE",    SUBTILIS_KEYWORD_CIRCLE,       true},
	{"CLEAR",     SUBTILIS_KEYWORD_CLEAR,        false},
	{"CLG",       SUBTILIS_KEYWORD_CLG,          true},
	{"CLOSE#",    SUBTILIS_KEYWORD_CLOSE_HASH,   true},
	{"CLS",       SUBTILIS_KEYWORD_CLS,          true},
	{"COLOR",     SUBTILIS_KEYWORD_COLOR,        true},
	{"COLOUR",    SUBTILIS_KEYWORD_COLOUR,       true},
	{"COS",       SUBTILIS_KEYWORD_COS,          true},
	{"COUNT",     SUBTILIS_KEYWORD_COUNT,        true},
	{"CRUNCH",    SUBTILIS_KEYWORD_CRUNCH,       false},
	{"DATA",      SUBTILIS_KEYWORD_DATA,         true},
	{"DEF",       SUBTILIS_KEYWORD_DEF,          true},
	{"DEG",       SUBTILIS_KEYWORD_DEG,          true},
	{"DELETE",    SUBTILIS_KEYWORD_DELETE,       false},
	{"DIM",       SUBTILIS_KEYWORD_DIM,          true},
	{"DIV",       SUBTILIS_KEYWORD_DIV,          true},
	{"DRAW",      SUBTILIS_KEYWORD_DRAW,         true},
	{"EDIT",      SUBTILIS_KEYWORD_EDIT,         false},
	{"ELLIPSE",   SUBTILIS_KEYWORD_ELLIPSE,      true},
	{"ELSE",      SUBTILIS_KEYWORD_ELSE,         true},
	{"END",       SUBTILIS_KEYWORD_END,          true},
	{"ENDCASE",   SUBTILIS_KEYWORD_ENDCASE,      true},
	{"ENDERROR",  SUBTILIS_KEYWORD_ENDERROR,     true},
	{"ENDIF",     SUBTILIS_KEYWORD_ENDIF,        true},
	{"ENDPROC",   SUBTILIS_KEYWORD_ENDPROC,      true},
	{"ENDWHILE",  SUBTILIS_KEYWORD_ENDWHILE,     true},
	{"EOF#",      SUBTILIS_KEYWORD_EOF_HASH,     true},
	{"EOR",       SUBTILIS_KEYWORD_EOR,          true},
	{"ERL",       SUBTILIS_KEYWORD_ERL,          false},
	{"ERR",       SUBTILIS_KEYWORD_ERR,          true},
	{"ERROR",     SUBTILIS_KEYWORD_ERROR,        true},
	{"EVAL",      SUBTILIS_KEYWORD_EVAL,         false},
	{"EXP",       SUBTILIS_KEYWORD_EXP,          true},
	{"EXT#",      SUBTILIS_KEYWORD_EXT_HASH,     true},
	{"FALSE",     SUBTILIS_KEYWORD_FALSE,        true},
	{"FILL",      SUBTILIS_KEYWORD_FILL,         true},
	{"FN",        SUBTILIS_KEYWORD_FN,           true},
	{"FOR",       SUBTILIS_KEYWORD_FOR,          true},
	{"GCOL",      SUBTILIS_KEYWORD_GCOL,         true},
	{"GET",       SUBTILIS_KEYWORD_GET,          true},
	{"GET$",      SUBTILIS_KEYWORD_GET_STR,      true},
	{"GET$#",     SUBTILIS_KEYWORD_GET_STR_HASH, true},
	{"GOSUB",     SUBTILIS_KEYWORD_GOSUB,        true},
	{"GOTO",      SUBTILIS_KEYWORD_GOTO,         true},
	{"HELP",      SUBTILIS_KEYWORD_HELP,         false},
	{"HIMEM",     SUBTILIS_KEYWORD_HIMEM,        false},
	{"IF",        SUBTILIS_KEYWORD_IF,           true},
	{"INKEY",     SUBTILIS_KEYWORD_INKEY,        true},
	{"INKEY$",    SUBTILIS_KEYWORD_INKEY_STR,    true},
	{"INPUT",     SUBTILIS_KEYWORD_INPUT,        true},
	{"INPUT#",    SUBTILIS_KEYWORD_INPUT_HASH,   true},
	{"INSTALL",   SUBTILIS_KEYWORD_INSTALL,      false},
	{"INSTR",     SUBTILIS_KEYWORD_INSTR,        true},
	{"INT",       SUBTILIS_KEYWORD_INT,          true},
	{"LEFT$",     SUBTILIS_KEYWORD_LEFT_STR,     true},
	{"LEN",       SUBTILIS_KEYWORD_LEN,          true},
	{"LET",       SUBTILIS_KEYWORD_LET,          true},
	{"LIBRARY",   SUBTILIS_KEYWORD_LIBRARY,      false},
	{"LINE",      SUBTILIS_KEYWORD_LINE,         true},
	{"LIST",      SUBTILIS_KEYWORD_LIST,         false},
	{"LISTO",     SUBTILIS_KEYWORD_LISTO,        false},
	{"LN",        SUBTILIS_KEYWORD_LN,           true},
	{"LOAD",      SUBTILIS_KEYWORD_LOAD,         false},
	{"LOCAL",     SUBTILIS_KEYWORD_LOCAL,        true},
	{"LOG",       SUBTILIS_KEYWORD_LOG,          true},
	{"LOMEM",     SUBTILIS_KEYWORD_LOMEM,        false},
	{"LVAR",      SUBTILIS_KEYWORD_LVAR,         false},
	{"MID$",      SUBTILIS_KEYWORD_MID_STR,      true},
	{"MOD",       SUBTILIS_KEYWORD_MOD,          true},
	{"MODE",      SUBTILIS_KEYWORD_MODE,         true},
	{"MOUSE",     SUBTILIS_KEYWORD_MOUSE,        true},
	{"MOVE",      SUBTILIS_KEYWORD_MOVE,         true},
	{"NEW",       SUBTILIS_KEYWORD_NEW,          false},
	{"NEXT",      SUBTILIS_KEYWORD_NEXT,         true},
	{"NOT",       SUBTILIS_KEYWORD_NOT,          true},
	{"OF",        SUBTILIS_KEYWORD_OF,           true},
	{"OFF",       SUBTILIS_KEYWORD_OFF,          true},
	{"OLD",       SUBTILIS_KEYWORD_OLD,          false},
	{"ON",        SUBTILIS_KEYWORD_ON,           true},
	{"ONERROR",   SUBTILIS_KEYWORD_ONERROR,      true},
	{"OPENIN",    SUBTILIS_KEYWORD_OPENIN,       true},
	{"OPENOUT",   SUBTILIS_KEYWORD_OPENOUT,      true},
	{"OPENUP",    SUBTILIS_KEYWORD_OPENUP,       true},
	{"OR",        SUBTILIS_KEYWORD_OR,           true},
	{"ORIGIN",    SUBTILIS_KEYWORD_ORIGIN,       true},
	{"OSCLI",     SUBTILIS_KEYWORD_OSCLI,        true},
	{"OTHERWISE", SUBTILIS_KEYWORD_OTHERWISE,    true},
	{"OVERLAY",   SUBTILIS_KEYWORD_OVERLAY,      false},
	{"PAGE",      SUBTILIS_KEYWORD_PAGE,         false},
	{"PI",        SUBTILIS_KEYWORD_PI,           true},
	{"PLOT",      SUBTILIS_KEYWORD_PLOT,         true},
	{"POINT",     SUBTILIS_KEYWORD_POINT,        true},
	{"POS",       SUBTILIS_KEYWORD_POS,          true},
	{"PRINT",     SUBTILIS_KEYWORD_PRINT,        true},
	{"PRINT#",    SUBTILIS_KEYWORD_PRINT_HASH,   true},
	{"PROC",      SUBTILIS_KEYWORD_PROC,         true},
	{"PTR#",      SUBTILIS_KEYWORD_PTR_HASH,     true},
	{"QUIT",      SUBTILIS_KEYWORD_QUIT,         true},
	{"RAD",       SUBTILIS_KEYWORD_RAD,          true},
	{"READ",      SUBTILIS_KEYWORD_READ,         true},
	{"RECTANGLE", SUBTILIS_KEYWORD_RECTANGLE,    true},
	{"REM",       SUBTILIS_KEYWORD_REM,          true},
	{"RENUMBER",  SUBTILIS_KEYWORD_RENUMBER,     false},
	{"REPEAT",    SUBTILIS_KEYWORD_REPEAT,       true},
	{"REPORT",    SUBTILIS_KEYWORD_REPORT,       true},
	{"REPORT$",   SUBTILIS_KEYWORD_REPORT_STR,   true},
	{"RESTORE",   SUBTILIS_KEYWORD_RESTORE,      true},
	{"RETURN",    SUBTILIS_KEYWORD_RETURN,       true},
	{"RIGHTS$",   SUBTILIS_KEYWORD_RIGHT_STR,    true},
	{"RND",       SUBTILIS_KEYWORD_RND,          true},
	{"RUN",       SUBTILIS_KEYWORD_RUN,          false},
	{"SAVE",      SUBTILIS_KEYWORD_SAVE,         false},
	{"SGN",       SUBTILIS_KEYWORD_SGN,          true},
	{"SIN",       SUBTILIS_KEYWORD_SIN,          true},
	{"SOUND",     SUBTILIS_KEYWORD_SOUND,        true},
	{"SPC",       SUBTILIS_KEYWORD_SPC,          true},
	{"SQR",       SUBTILIS_KEYWORD_SQR,          true},
	{"STEP",      SUBTILIS_KEYWORD_STEP,         true},
	{"STEREO",    SUBTILIS_KEYWORD_STEREO,       true},
	{"STOP",      SUBTILIS_KEYWORD_STOP,         true},
	{"STR$",      SUBTILIS_KEYWORD_STRS,         true},
	{"STRING$",   SUBTILIS_KEYWORD_STRING_STR,   true},
	{"SUM",       SUBTILIS_KEYWORD_SUM,          true},
	{"SUMLEN",    SUBTILIS_KEYWORD_SUMLEN,       true},
	{"SWAP",      SUBTILIS_KEYWORD_SWAP,         true},
	{"SYS",       SUBTILIS_KEYWORD_SYS,          true},
	{"TAB",       SUBTILIS_KEYWORD_TAB,          true},
	{"TAN",       SUBTILIS_KEYWORD_TAN,          true},
	{"TEMPO",     SUBTILIS_KEYWORD_TEMPO,        true},
	{"TEXTLOAD",  SUBTILIS_KEYWORD_TEXTLOAD,     false},
	{"TEXTSAVE",  SUBTILIS_KEYWORD_TEXTSAVE,     false},
	{"THEN",      SUBTILIS_KEYWORD_THEN,         true},
	{"TIME",      SUBTILIS_KEYWORD_TIME,         true},
	{"TIME$",     SUBTILIS_KEYWORD_TIME_STR,     true},
	{"TINT",      SUBTILIS_KEYWORD_TINT,         true},
	{"TO",        SUBTILIS_KEYWORD_TO,           true},
	{"TOP",       SUBTILIS_KEYWORD_TOP,          false},
	{"TRACE",     SUBTILIS_KEYWORD_TRACE,        false},
	{"TRUE",      SUBTILIS_KEYWORD_TRUE,         true},
	{"TWIN",      SUBTILIS_KEYWORD_TWIN,         false},
	{"UNTIL",     SUBTILIS_KEYWORD_UNTIL,        true},
	{"USR",       SUBTILIS_KEYWORD_UNTIL,        true},
	{"VAL",       SUBTILIS_KEYWORD_VAL,          true},
	{"VDU",       SUBTILIS_KEYWORD_VDU,          true},
	{"VOICES",    SUBTILIS_KEYWORD_VOICES,       true},
	{"VPOS",      SUBTILIS_KEYWORD_VPOS,         true},
	{"WAIT",      SUBTILIS_KEYWORD_WAIT,         true},
	{"WHEN",      SUBTILIS_KEYWORD_WHEN,         true},
	{"WHILE",     SUBTILIS_KEYWORD_WHILE,        true},
	{"WIDTH",     SUBTILIS_KEYWORD_WIDTH,        true},
};

/* clang-format on */
