/*
 * Copyright (c) 2020 Mark Ryan
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "type_if.h"

/*
 * This is not a real type.  It only exists to reserve stack space
 * for use by code generated by the compiler.
 */

/* clang-format off */
subtilis_type_if subtilis_type_if_local_buffer = {
	.is_const = false,
	.is_numeric = true,
	.is_integer = true,
	.param_type = SUBTILIS_IR_REG_TYPE_INTEGER,
	.size = NULL,
	.data_size = NULL,
	.zero = NULL,
	.zero_ref = NULL,
	.new_ref = NULL,
	.assign_ref = NULL,
	.top_bit = NULL,
	.zero_reg = NULL,
	.const_of = NULL,
	.array_of = NULL,
	.element_type = NULL,
	.exp_to_var = NULL,
	.copy_var = NULL,
	.dup = NULL,
	.assign_reg = NULL,
	.assign_mem = NULL,
	.indexed_write = NULL,
	.indexed_add = NULL,
	.indexed_sub = NULL,
	.indexed_read = NULL,
	.load_mem = NULL,
	.to_int32 = NULL,
	.to_float64 = NULL,
	.coerce = NULL,
	.unary_minus = NULL,
	.add = NULL,
	.mul = NULL,
	.and = NULL,
	.or = NULL,
	.eor = NULL,
	.not = NULL,
	.eq = NULL,
	.neq = NULL,
	.sub = NULL,
	.div = NULL,
	.mod = NULL,
	.gt = NULL,
	.lte = NULL,
	.lt = NULL,
	.gte = NULL,
	.pow = NULL,
	.lsl = NULL,
	.lsr = NULL,
	.asr = NULL,
	.abs = NULL,
	.sgn = NULL,
	.call = NULL,
	.ret = NULL,
	.print = NULL,
	.destructor = NULL,
};

/* clang-format on */
