language: c

before_install:
    - eval "${MATRIX_EVAL}"

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"

before_script:
  - echo "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main" | sudo tee -a /etc/apt/sources.list
  - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install clang-format-3.9 -y


install:
 - wget https://raw.githubusercontent.com/torvalds/linux/master/scripts/checkpatch.pl
 - wget https://raw.githubusercontent.com/torvalds/linux/master/scripts/spelling.txt
 - wget https://raw.githubusercontent.com/torvalds/linux/master/scripts/const_structs.checkpatch

script:
 - CFLAGS="-g -fsanitize=address -fno-omit-frame-pointer -Wall -Werror" make
 - CFLAGS="-g -fsanitize=address -fno-omit-frame-pointer -Wall -Werror" make check
 - perl checkpatch.pl --no-tree -f --strict --show-types --ignore NEW_TYPEDEFS --ignore PREFER_KERNEL_TYPES --ignore SPLIT_STRING --ignore UNNECESSARY_PARENTHESES --ignore SPDX_LICENSE_TAG --ignore OPEN_ENDED_LINE *.c *.h
 - ./check-format.sh
